
import { Branch, SalesData, MenuItem, Staff, SystemUser, Role } from './types';

export const MOCK_BRANCHES: Branch[] = [
  { 
    id: '1', name: 'Makati Central', location: 'Ayala Ave, Makati', manager: 'Juan Dela Cruz', status: 'Open', dailyRevenue: 45000, ordersCount: 120, topSellingItem: 'Adobo Rice Bowl',
    expenses: { labor: 12000, cogs: 15000, operational: 5000 }
  },
  { 
    id: '2', name: 'BGC Stopover', location: '32nd St, Taguig', manager: 'Maria Santos', status: 'Open', dailyRevenue: 52000, ordersCount: 145, topSellingItem: 'Sinigang na Hipon',
    expenses: { labor: 14000, cogs: 18000, operational: 6000 }
  },
  { 
    id: '3', name: 'Quezon City Main', location: 'Tomas Morato, QC', manager: 'Pedro Penduko', status: 'Maintenance', dailyRevenue: 0, ordersCount: 0, topSellingItem: 'N/A',
    expenses: { labor: 5000, cogs: 0, operational: 4000 }
  },
  { 
    id: '4', name: 'Alabang Hub', location: 'Filinvest, Muntinlupa', manager: 'Elena Reyes', status: 'Open', dailyRevenue: 38000, ordersCount: 95, topSellingItem: 'Crispy Pata',
    expenses: { labor: 10000, cogs: 12000, operational: 4500 }
  },
];

export const MOCK_ROLES: Role[] = [
  { id: 'r1', name: 'Super Admin', description: 'Full system access across all branches.', permissions: ['all'] },
  { id: 'r2', name: 'Finance Manager', description: 'Access to revenue and cost reports.', permissions: ['read_financials', 'export_data'] },
  { id: 'r3', name: 'Branch Manager', description: 'Manage specific branch inventory and staff.', permissions: ['manage_branch', 'manage_inventory', 'manage_staff'] },
];

export const MOCK_SYSTEM_USERS: SystemUser[] = [
  { id: 'u1', name: 'Juan Luna', email: 'juan.luna@restoadmin.ph', roleId: 'r1', lastActive: '2 mins ago', avatar: 'https://picsum.photos/40/40?random=10' },
  { id: 'u2', name: 'Maria Makiling', email: 'maria.m@restoadmin.ph', roleId: 'r3', lastActive: '1 hour ago', avatar: 'https://picsum.photos/40/40?random=11' },
  { id: 'u3', name: 'Jose Rizal', email: 'jose.r@restoadmin.ph', roleId: 'r2', lastActive: 'Yesterday', avatar: 'https://picsum.photos/40/40?random=12' },
];

export const MOCK_INVENTORY: MenuItem[] = [
  { id: 'i1', name: 'Bacon / Ham / Pepperoni', category: 'Specialized Proteins & Cured Meats', price: 420, stock: 36, unit: 'kg', branchId: '1' },
  { id: 'i2', name: 'Sausage (Chorizo/Italian/Longganisa)', category: 'Specialized Proteins & Cured Meats', price: 350, stock: 42, unit: 'kg', branchId: '2' },
  { id: 'i3', name: 'Duck / Quail', category: 'Specialized Proteins & Cured Meats', price: 390, stock: 28, unit: 'kg', branchId: '4' },
  { id: 'i4', name: 'Lamb Chops / Shacks', category: 'Specialized Proteins & Cured Meats', price: 680, stock: 14, unit: 'kg', branchId: '1' },
  { id: 'i5', name: 'Mussels / Clams / Scallops', category: 'Specialized Proteins & Cured Meats', price: 510, stock: 20, unit: 'kg', branchId: '2' },
  { id: 'i6', name: 'Salmon Fillet / Smoked Salmon', category: 'Specialized Proteins & Cured Meats', price: 780, stock: 18, unit: 'kg', branchId: '4' },
  { id: 'i7', name: 'Corned Beef', category: 'Specialized Proteins & Cured Meats', price: 190, stock: 55, unit: 'can', branchId: '1' },
  { id: 'i8', name: 'Luncheon Meat', category: 'Specialized Proteins & Cured Meats', price: 160, stock: 63, unit: 'can', branchId: '2' },
  { id: 'i9', name: 'Fresh Milk / Evaporated Milk', category: 'Dairy & Cheeses', price: 95, stock: 70, unit: 'L', branchId: '4' },
  { id: 'i10', name: 'All-purpose Cream / Heavy Cream', category: 'Dairy & Cheeses', price: 125, stock: 44, unit: 'L', branchId: '1' },
  { id: 'i11', name: 'Cheese (Cheddar/Mozzarella/Parmesan/Quickmelt)', category: 'Dairy & Cheeses', price: 460, stock: 32, unit: 'kg', branchId: '2' },
  { id: 'i12', name: 'Cream Cheese', category: 'Dairy & Cheeses', price: 240, stock: 26, unit: 'kg', branchId: '4' },
  { id: 'i13', name: 'Sour Cream', category: 'Dairy & Cheeses', price: 170, stock: 22, unit: 'kg', branchId: '1' },
  { id: 'i14', name: 'Yogurt', category: 'Dairy & Cheeses', price: 130, stock: 48, unit: 'L', branchId: '2' },
  { id: 'i15', name: 'Condensed Milk', category: 'Dairy & Cheeses', price: 88, stock: 66, unit: 'can', branchId: '4' },
  { id: 'i16', name: 'Paprika (Smoked/Sweet)', category: 'Herbs & Spices (Dry)', price: 420, stock: 15, unit: 'kg', branchId: '1' },
  { id: 'i17', name: 'Cumin', category: 'Herbs & Spices (Dry)', price: 390, stock: 19, unit: 'kg', branchId: '2' },
  { id: 'i18', name: 'Turmeric', category: 'Herbs & Spices (Dry)', price: 280, stock: 25, unit: 'kg', branchId: '4' },
  { id: 'i19', name: 'Cinnamon (Powder/Sticks)', category: 'Herbs & Spices (Dry)', price: 340, stock: 18, unit: 'kg', branchId: '1' },
  { id: 'i20', name: 'Oregano', category: 'Herbs & Spices (Dry)', price: 260, stock: 21, unit: 'kg', branchId: '2' },
  { id: 'i21', name: 'Basil', category: 'Herbs & Spices (Dry)', price: 250, stock: 17, unit: 'kg', branchId: '4' },
  { id: 'i22', name: 'Thyme', category: 'Herbs & Spices (Dry)', price: 270, stock: 16, unit: 'kg', branchId: '1' },
  { id: 'i23', name: 'Rosemary', category: 'Herbs & Spices (Dry)', price: 275, stock: 14, unit: 'kg', branchId: '2' },
  { id: 'i24', name: 'Chili Flakes', category: 'Herbs & Spices (Dry)', price: 320, stock: 23, unit: 'kg', branchId: '4' },
  { id: 'i25', name: 'Star Anise', category: 'Herbs & Spices (Dry)', price: 360, stock: 12, unit: 'kg', branchId: '1' },
  { id: 'i26', name: 'Curry Powder', category: 'Herbs & Spices (Dry)', price: 300, stock: 27, unit: 'kg', branchId: '2' },
  { id: 'i27', name: 'Five-Spice Powder', category: 'Herbs & Spices (Dry)', price: 330, stock: 11, unit: 'kg', branchId: '4' },
  { id: 'i28', name: 'Barbecue Sauce', category: 'Specialty Sauces & Condiments', price: 210, stock: 38, unit: 'bottle', branchId: '1' },
  { id: 'i29', name: 'Hoisin Sauce', category: 'Specialty Sauces & Condiments', price: 230, stock: 30, unit: 'bottle', branchId: '2' },
  { id: 'i30', name: 'Teriyaki Sauce', category: 'Specialty Sauces & Condiments', price: 220, stock: 34, unit: 'bottle', branchId: '4' },
  { id: 'i31', name: 'Mirin', category: 'Specialty Sauces & Condiments', price: 260, stock: 24, unit: 'bottle', branchId: '1' },
  { id: 'i32', name: 'Sake (Cooking Wine)', category: 'Specialty Sauces & Condiments', price: 340, stock: 20, unit: 'bottle', branchId: '2' },
  { id: 'i33', name: 'Rice Wine Vinegar', category: 'Specialty Sauces & Condiments', price: 195, stock: 41, unit: 'bottle', branchId: '4' },
  { id: 'i34', name: 'Honey', category: 'Specialty Sauces & Condiments', price: 360, stock: 22, unit: 'kg', branchId: '1' },
  { id: 'i35', name: 'Maple Syrup', category: 'Specialty Sauces & Condiments', price: 480, stock: 16, unit: 'bottle', branchId: '2' },
  { id: 'i36', name: 'Peanut Butter', category: 'Specialty Sauces & Condiments', price: 310, stock: 29, unit: 'jar', branchId: '4' },
  { id: 'i37', name: 'Sesame Seeds', category: 'Specialty Sauces & Condiments', price: 290, stock: 33, unit: 'kg', branchId: '1' },
  { id: 'i38', name: 'Sriracha / Chili Garlic Oil', category: 'Specialty Sauces & Condiments', price: 245, stock: 31, unit: 'bottle', branchId: '2' },
  { id: 'i39', name: 'Tahini', category: 'Specialty Sauces & Condiments', price: 390, stock: 13, unit: 'jar', branchId: '4' },
  { id: 'i40', name: 'Pesto Sauce', category: 'Specialty Sauces & Condiments', price: 330, stock: 18, unit: 'jar', branchId: '1' },
  { id: 'i41', name: 'Mushrooms (Button/Shiitake/Oyster)', category: 'More Vegetables & Legumes', price: 220, stock: 37, unit: 'kg', branchId: '2' },
  { id: 'i42', name: 'Celery', category: 'More Vegetables & Legumes', price: 120, stock: 40, unit: 'kg', branchId: '4' },
  { id: 'i43', name: 'Broccoli / Cauliflower', category: 'More Vegetables & Legumes', price: 180, stock: 26, unit: 'kg', branchId: '1' },
  { id: 'i44', name: 'Zucchini', category: 'More Vegetables & Legumes', price: 160, stock: 24, unit: 'kg', branchId: '2' },
  { id: 'i45', name: 'Spinach', category: 'More Vegetables & Legumes', price: 140, stock: 32, unit: 'kg', branchId: '4' },
  { id: 'i46', name: 'Asparagus', category: 'More Vegetables & Legumes', price: 260, stock: 19, unit: 'kg', branchId: '1' },
  { id: 'i47', name: 'Corn (Kernels/Baby Corn)', category: 'More Vegetables & Legumes', price: 155, stock: 35, unit: 'kg', branchId: '2' },
  { id: 'i48', name: 'Garbanzos / Chickpeas', category: 'More Vegetables & Legumes', price: 130, stock: 43, unit: 'kg', branchId: '4' },
  { id: 'i49', name: 'Green Peas', category: 'More Vegetables & Legumes', price: 145, stock: 39, unit: 'kg', branchId: '1' },
  { id: 'i50', name: 'Kidney Beans / Black Beans', category: 'More Vegetables & Legumes', price: 150, stock: 47, unit: 'kg', branchId: '2' },
  { id: 'i51', name: 'Radish', category: 'More Vegetables & Legumes', price: 115, stock: 28, unit: 'kg', branchId: '4' },
  { id: 'i52', name: 'Bitter Gourd (Ampalaya)', category: 'More Vegetables & Legumes', price: 125, stock: 21, unit: 'kg', branchId: '1' },
  { id: 'i53', name: 'Vanilla Extract', category: 'Baking & Miscellaneous', price: 290, stock: 17, unit: 'bottle', branchId: '2' },
  { id: 'i54', name: 'Cocoa Powder', category: 'Baking & Miscellaneous', price: 260, stock: 23, unit: 'kg', branchId: '4' },
  { id: 'i55', name: 'Chocolate Chips / Cooking Chocolate', category: 'Baking & Miscellaneous', price: 300, stock: 25, unit: 'kg', branchId: '1' },
  { id: 'i56', name: 'Coconut Milk / Coconut Cream', category: 'Baking & Miscellaneous', price: 105, stock: 52, unit: 'L', branchId: '2' },
  { id: 'i57', name: 'Gelatin Powder', category: 'Baking & Miscellaneous', price: 210, stock: 16, unit: 'kg', branchId: '4' },
  { id: 'i58', name: 'Food Coloring', category: 'Baking & Miscellaneous', price: 180, stock: 20, unit: 'bottle', branchId: '1' },
  { id: 'i59', name: 'Nori (Seaweed Sheets)', category: 'Baking & Miscellaneous', price: 240, stock: 27, unit: 'pack', branchId: '2' },
  { id: 'i60', name: 'Pickles / Relish', category: 'Baking & Miscellaneous', price: 190, stock: 31, unit: 'jar', branchId: '4' },
  { id: 'i61', name: 'Olives (Black/Green)', category: 'Baking & Miscellaneous', price: 270, stock: 18, unit: 'jar', branchId: '1' },
  { id: 'i62', name: 'Capers', category: 'Baking & Miscellaneous', price: 350, stock: 10, unit: 'jar', branchId: '2' },
  { id: 'i63', name: 'Gochujang (Korean Red Chili Paste)', category: 'Sauces, Pastes & Liquids', price: 280, stock: 35, unit: 'tub', branchId: '4' },
  { id: 'i64', name: 'Doenjang (Fermented Soybean Paste)', category: 'Sauces, Pastes & Liquids', price: 265, stock: 29, unit: 'tub', branchId: '1' },
  { id: 'i65', name: 'Ssamjang (Spicy Dipping Paste)', category: 'Sauces, Pastes & Liquids', price: 255, stock: 24, unit: 'tub', branchId: '2' },
  { id: 'i66', name: 'Chunjang (Black Bean Paste)', category: 'Sauces, Pastes & Liquids', price: 245, stock: 22, unit: 'tub', branchId: '4' },
  { id: 'i67', name: 'Rice Syrup (Mulyeot)', category: 'Sauces, Pastes & Liquids', price: 230, stock: 19, unit: 'bottle', branchId: '1' },
  { id: 'i68', name: 'Mirin / Cooking Rice Wine (Mat-sul)', category: 'Sauces, Pastes & Liquids', price: 275, stock: 20, unit: 'bottle', branchId: '2' },
  { id: 'i69', name: 'Korean Soy Sauce (Soup Soy Sauce vs. Regular)', category: 'Sauces, Pastes & Liquids', price: 210, stock: 33, unit: 'bottle', branchId: '4' },
  { id: 'i70', name: 'Roasted Sesame Oil', category: 'Sauces, Pastes & Liquids', price: 320, stock: 21, unit: 'bottle', branchId: '1' },
  { id: 'i71', name: 'Fish Sauce (Anchovy or Sand Lance)', category: 'Sauces, Pastes & Liquids', price: 175, stock: 38, unit: 'bottle', branchId: '2' },
  { id: 'i72', name: 'Plum Syrup (Maesil-cheong)', category: 'Sauces, Pastes & Liquids', price: 360, stock: 14, unit: 'bottle', branchId: '4' },
  { id: 'i73', name: 'Gochugaru (Korean Chili Flakes)', category: 'Spices & Dry Goods', price: 410, stock: 17, unit: 'kg', branchId: '1' },
  { id: 'i74', name: 'Roasted Sesame Seeds', category: 'Spices & Dry Goods', price: 300, stock: 25, unit: 'kg', branchId: '2' },
  { id: 'i75', name: 'Dasida (Korean Beef/Anchovy Stock Powder)', category: 'Spices & Dry Goods', price: 260, stock: 31, unit: 'pack', branchId: '4' },
  { id: 'i76', name: 'Dried Kelp (Kombu/Dashima)', category: 'Spices & Dry Goods', price: 280, stock: 22, unit: 'pack', branchId: '1' },
  { id: 'i77', name: 'Dried Anchovies (Large for broth, Small for side dishes)', category: 'Spices & Dry Goods', price: 340, stock: 18, unit: 'kg', branchId: '2' },
  { id: 'i78', name: 'Sweet Rice Flour (Sticky Rice Flour)', category: 'Spices & Dry Goods', price: 150, stock: 37, unit: 'kg', branchId: '4' },
  { id: 'i79', name: 'Potato Starch / Tapioca Starch', category: 'Spices & Dry Goods', price: 140, stock: 42, unit: 'kg', branchId: '1' },
  { id: 'i80', name: 'Wheat Flour (Meduryeok)', category: 'Spices & Dry Goods', price: 95, stock: 54, unit: 'kg', branchId: '2' },
  { id: 'i81', name: 'Dried Shiitake Mushrooms', category: 'Spices & Dry Goods', price: 420, stock: 13, unit: 'kg', branchId: '4' },
  { id: 'i82', name: 'Nori Sheets (Gim)', category: 'Spices & Dry Goods', price: 235, stock: 26, unit: 'pack', branchId: '1' },
  { id: 'i83', name: 'Samgyeopsal (Pork Belly - Thick/Thin)', category: 'Meat & Proteins (K-BBQ Specific Cuts)', price: 420, stock: 28, unit: 'kg', branchId: '2' },
  { id: 'i84', name: 'Moksal (Pork Neck/Shoulder)', category: 'Meat & Proteins (K-BBQ Specific Cuts)', price: 390, stock: 24, unit: 'kg', branchId: '4' },
  { id: 'i85', name: 'Chadolbagi (Thinly Sliced Beef Brisket)', category: 'Meat & Proteins (K-BBQ Specific Cuts)', price: 560, stock: 18, unit: 'kg', branchId: '1' },
  { id: 'i86', name: 'Galbi (Beef Short Ribs)', category: 'Meat & Proteins (K-BBQ Specific Cuts)', price: 690, stock: 12, unit: 'kg', branchId: '2' },
  { id: 'i87', name: 'Bul-gogi (Thinly Sliced Marinated Beef)', category: 'Meat & Proteins (K-BBQ Specific Cuts)', price: 540, stock: 20, unit: 'kg', branchId: '4' },
  { id: 'i88', name: 'Daepae Samgyeopsal (Rolled Paper-thin Pork)', category: 'Meat & Proteins (K-BBQ Specific Cuts)', price: 430, stock: 27, unit: 'kg', branchId: '1' },
  { id: 'i89', name: 'Dwaeji Galbi (Marinated Pork Ribs)', category: 'Meat & Proteins (K-BBQ Specific Cuts)', price: 470, stock: 19, unit: 'kg', branchId: '2' },
  { id: 'i90', name: 'Chicken Gizzards', category: 'Meat & Proteins (K-BBQ Specific Cuts)', price: 210, stock: 33, unit: 'kg', branchId: '4' },
  { id: 'i91', name: 'Silkworm Pupae (Beondegi)', category: 'Meat & Proteins (K-BBQ Specific Cuts)', price: 290, stock: 9, unit: 'can', branchId: '1' },
  { id: 'i92', name: 'Dangmyeon (Sweet Potato Starch Noodles / Glass Noodles)', category: 'Noodles & Grains', price: 190, stock: 44, unit: 'pack', branchId: '2' },
  { id: 'i93', name: 'Ramyun (Instant Noodles)', category: 'Noodles & Grains', price: 135, stock: 58, unit: 'pack', branchId: '4' },
  { id: 'i94', name: 'Somyeon (Thin Wheat Noodles)', category: 'Noodles & Grains', price: 175, stock: 36, unit: 'pack', branchId: '1' },
  { id: 'i95', name: 'Udon Noodles', category: 'Noodles & Grains', price: 165, stock: 40, unit: 'pack', branchId: '2' },
  { id: 'i96', name: 'Jajangmyeon Noodles', category: 'Noodles & Grains', price: 180, stock: 29, unit: 'pack', branchId: '4' },
  { id: 'i97', name: 'Short-grain White Rice (Ssal)', category: 'Noodles & Grains', price: 65, stock: 90, unit: 'kg', branchId: '1' },
  { id: 'i98', name: 'Purple Rice / Mixed Grains (Japgokbap)', category: 'Noodles & Grains', price: 95, stock: 54, unit: 'kg', branchId: '2' },
  { id: 'i99', name: 'Tteok (Rice Cakes - Cylindrical or Sliced)', category: 'Noodles & Grains', price: 220, stock: 23, unit: 'kg', branchId: '4' },
  { id: 'i100', name: 'Korean Radish (Mu)', category: 'Fresh Produce & Vegetables', price: 110, stock: 47, unit: 'kg', branchId: '1' },
  { id: 'i101', name: 'Napa Cabbage (Baechu - for Kimchi)', category: 'Fresh Produce & Vegetables', price: 95, stock: 62, unit: 'kg', branchId: '2' },
  { id: 'i102', name: 'Perilla Leaves (Kkaennip)', category: 'Fresh Produce & Vegetables', price: 85, stock: 34, unit: 'bundle', branchId: '4' },
  { id: 'i103', name: 'Enoki Mushrooms', category: 'Fresh Produce & Vegetables', price: 145, stock: 25, unit: 'pack', branchId: '1' },
  { id: 'i104', name: 'King Oyster Mushrooms', category: 'Fresh Produce & Vegetables', price: 170, stock: 21, unit: 'kg', branchId: '2' },
  { id: 'i105', name: 'Garlic Chives (Bucha)', category: 'Fresh Produce & Vegetables', price: 120, stock: 28, unit: 'bundle', branchId: '4' },
  { id: 'i106', name: 'Bean Sprouts (Sukju-namul)', category: 'Fresh Produce & Vegetables', price: 90, stock: 53, unit: 'kg', branchId: '1' },
  { id: 'i107', name: 'Soybean Sprouts (Kong-namul)', category: 'Fresh Produce & Vegetables', price: 98, stock: 45, unit: 'kg', branchId: '2' },
  { id: 'i108', name: 'Scallions / Green Onions (Dae-pa)', category: 'Fresh Produce & Vegetables', price: 100, stock: 39, unit: 'kg', branchId: '4' },
  { id: 'i109', name: 'Kimchi (Aged/Matured vs. Fresh)', category: 'Fresh Produce & Vegetables', price: 210, stock: 30, unit: 'kg', branchId: '1' },
  { id: 'i110', name: 'Pickled Yellow Radish (Danmuji)', category: 'Fresh Produce & Vegetables', price: 165, stock: 24, unit: 'pack', branchId: '2' },
  { id: 'i111', name: 'Crown Daisy (Ssukgat)', category: 'Fresh Produce & Vegetables', price: 115, stock: 20, unit: 'bundle', branchId: '4' },
];

export const MOCK_STAFF: Staff[] = [
  { id: 's1', name: 'Juan Dela Cruz', role: 'Manager', status: 'Active', branchId: '1', rating: 4.8, email: 'juan.dc@restoadmin.ph', joinedDate: '2023-01-15' },
  { id: 's2', name: 'Liza Soberano', role: 'Server', status: 'Active', branchId: '1', rating: 4.9, email: 'liza.s@restoadmin.ph', joinedDate: '2023-05-20' },
  { id: 's3', name: 'Rico Blanco', role: 'Chef', status: 'On Break', branchId: '1', rating: 4.7, email: 'rico.b@restoadmin.ph', joinedDate: '2023-02-10' },
  { id: 's4', name: 'Maria Santos', role: 'Manager', status: 'Active', branchId: '2', rating: 4.6, email: 'maria.s@restoadmin.ph', joinedDate: '2022-11-05' },
  { id: 's5', name: 'Anton Diaz', role: 'Chef', status: 'Active', branchId: '2', rating: 4.5, email: 'anton.d@restoadmin.ph', joinedDate: '2023-03-12' },
  { id: 's6', name: 'Ben Tulfo', role: 'Server', status: 'Off Duty', branchId: '2', rating: 4.2, email: 'ben.t@restoadmin.ph', joinedDate: '2024-01-15' },
  { id: 's7', name: 'Elena Reyes', role: 'Manager', status: 'Active', branchId: '4', rating: 4.9, email: 'elena.r@restoadmin.ph', joinedDate: '2023-06-01' },
  { id: 's8', name: 'Vhong Navarro', role: 'Chef', status: 'Active', branchId: '4', rating: 4.4, email: 'vhong.n@restoadmin.ph', joinedDate: '2023-08-25' },
  { id: 's9', name: 'Anne Curtis', role: 'Server', status: 'Active', branchId: '4', rating: 5.0, email: 'anne.c@restoadmin.ph', joinedDate: '2023-09-12' },
  { id: 's10', name: 'Pedro Penduko', role: 'Manager', status: 'Off Duty', branchId: '3', rating: 4.3, email: 'pedro.p@restoadmin.ph', joinedDate: '2023-11-20' },
];

/** Sample data for Total Sales time-series chart when API returns empty */
export const SALES_CHART_DATA: SalesData[] = [
  { name: 'Mon', sales: 42500, expenses: 18200 },
  { name: 'Tue', sales: 38100, expenses: 16800 },
  { name: 'Wed', sales: 45200, expenses: 19500 },
  { name: 'Thu', sales: 39800, expenses: 17100 },
  { name: 'Fri', sales: 52100, expenses: 22400 },
  { name: 'Sat', sales: 58900, expenses: 25300 },
  { name: 'Sun', sales: 46700, expenses: 20100 },
];
